Baikal\ModelBundle\Entity\AbstractUser:
    #type: entity
    type: mappedSuperclass
    table: users
    repositoryClass: Baikal\ModelBundle\Entity\Repository\UserRepository
    entityListeners:
        Baikal\ModelBundle\Entity\Listener\UserListener: ~
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY

    fields:

        username:
            type: string
            length: 255
            unique: true
            nullable: true

        digesta1:
            type: string
            length: 200
            nullable: true

        roles:
            type: simple_array
            #nullable: false
            nullable: true

    lifecycleCallbacks: {  }
