services:
    baikal.model.sabredav_password_encoder:
        class: Baikal\ModelBundle\Services\SabreDavPasswordEncoder
        arguments:
            - %baikal.dav_realm%

    baikal.repository.calendar:
        class: Baikal\ModelBundle\Entity\Repository\CalendarRepository
        arguments:
            - @doctrine.orm.entity_manager

    baikal.repository.event:
        class: Baikal\ModelBundle\Entity\Repository\EventRepository
        arguments:
            - @doctrine.orm.entity_manager

    baikal.repository.addressbook:
        class: Baikal\ModelBundle\Entity\Repository\AddressbookRepository
        arguments:
            - @doctrine.orm.entity_manager

    baikal.repository.contact:
        class: Baikal\ModelBundle\Entity\Repository\AddressbookContactRepository
        arguments:
            - @doctrine.orm.entity_manager

    baikal.repository.oauthclient:
        class: Baikal\ModelBundle\Entity\Repository\OAuthClientRepository
        arguments:
            - @doctrine.orm.entity_manager

    baikal.repository.oauthaccesstoken:
        class: Baikal\ModelBundle\Entity\Repository\OAuthAccessTokenRepository
        arguments:
            - @doctrine.orm.entity_manager

    baikal.doctrine.entity_listener_resolver:
        class: Baikal\ModelBundle\Doctrine\EntityListenerResolver
        arguments:
            - @service_container

    baikal.entity_listener.user:
        class: Baikal\ModelBundle\Entity\Listener\UserListener
        arguments:
            - @baikal.repository.calendar
            - @baikal.repository.addressbook
        tags:
            -  { name: doctrine.entity_listener }

    baikal.entity_listener.event:
        class: Baikal\ModelBundle\Entity\Listener\EventListener
        arguments: ~
        tags:
            -  { name: doctrine.entity_listener }